name: Python CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install numpy pillow pytest mypy flake8 black
      - name: Lint with flake8 (Линтер)
        run: flake8 src/ --ignore=E203,E501
      - name: Format check with black (Форматтер)
        run: black --check src/
      - name: Type check (Mypy)
        run: mypy src/
      - name: Run tests (Тесты)
        run: PYTHONPATH=src pytest tests/
